<a href="https://colab.research.google.com/github/codewithUswaFatima/urdu-ocr-codesaviours-si26-Uswa/blob/main/SI26_Week1_Uswa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**What is OCR (Optical Character Recognition)?**
Optical Character Recognition (OCR) is a technology that scans printed or handwritten text from images, PDFs, or documents and converts it into editable and searchable digital text. Instead of manually typing the content, OCR automatically recognizes the characters and extracts the text. OCR is widely used for digitizing books, forms, invoices, historical documents, and other paper-based records.

**Why is Urdu OCR harder than English OCR?**
Urdu OCR is more challenging than English OCR because Urdu is written in a cursive script where most letters are connected to each other. Many Urdu letters have very similar shapes and differ only by the number or position of dots, making them difficult to recognize accurately. In addition, different fonts, handwriting styles, image quality, and complex document layouts make Urdu OCR more difficult than English OCR. OCR systems usually perform preprocessing, segmentation, and character recognition to improve the accuracy of Urdu text extraction.

**What are 2 real-world situations where Urdu OCR would be useful?**
Urdu OCR is very useful for visually impaired people because it can extract text from books or documents and convert it into speech using text-to-speech technology. It is also useful for government offices, libraries, and legal organizations where thousands of Urdu documents, gazettes, and official records need to be digitized and stored in searchable electronic form. This saves time, reduces manual work, and makes documents easier to search and manage.

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
import zipfile
import os

zip_path = "/content/drive/MyDrive/archive (9).zip"

extract_path = "/content/dataset"

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_path)

print("Dataset Extracted Successfully!")

Dataset Extracted Successfully!

In [4]:
import os

print(os.listdir("/content/dataset"))

['main.csv', 'urdu_ocr_data']

In [5]:
import pandas as pd

df = pd.read_csv("/content/dataset/main.csv")

df.head()

   Unnamed: 0  file_name                                               text
0           0     /0.png  پشاور،بنوں (نمائندہ جنگ،اے ایف پی) بنوں میں اق...
1           1     /1.png     اسکے ساتھ ملحقہ علاقے کے عوام نے بجلی و گیس \n
2           2    /10.png  نے بجلی وگیس کی لوڈشیڈنگ کیخلاف مظاہرہ کیا۔ مظ...
3           3   /100.png  نہیں آ یا۔ آخریہ کونسا مذہب ہے؟کیا اسلام کے نا...
4           4  /1000.png   ضرور ہے۔ انہوں نے کہا کہ میرا احمدیوں سے کوئی \n

In [6]:
print("Total Images:", len(df))

Total Images: 10063

In [7]:
import os

folders = [
    "/content/data/raw/dataset",
    "/content/data/raw/newspaper",
    "/content/data/raw/synthetic"
]

for folder in folders:
    os.makedirs(folder, exist_ok=True)

print("Folders created!")

Folders created!

In [8]:
import os

print(os.listdir("/content/dataset/urdu_ocr_data"))

['line_undegraded', 'realgt']

In [10]:
print(df.columns.tolist())

['Unnamed: 0', 'file_name', 'text']

In [11]:
import shutil
import os

image_folder = "/content/dataset/urdu_ocr_data/line_undegraded/line_undegraded"

selected = df.head(50)

for _, row in selected.iterrows():

    filename = os.path.basename(row["file_name"])

    shutil.copy(
        os.path.join(image_folder, filename),
        "/content/data/raw/dataset"
    )

print("50 dataset images copied!")

50 dataset images copied!

In [12]:
import zipfile

with zipfile.ZipFile("/content/drive/MyDrive/screenshots/screenshots.zip","r") as zip_ref:
    zip_ref.extractall("/content/data/raw/newspaper")

print("30 newspaper images extracted!")

30 newspaper images extracted!

In [13]:
import zipfile

with zipfile.ZipFile("/content/drive/MyDrive/synthetic.zip","r") as zip_ref:
    zip_ref.extractall("/content/data/raw/synthetic")

print("20 synthetic images extracted!")

20 synthetic images extracted!

In [15]:
print(os.listdir("/content/data/raw/newspaper/screenshots")[:10])
print("Total:", len(os.listdir("/content/data/raw/newspaper/screenshots")))

['WhatsApp Image 2026-07-02 at 3.16.48 PM.jpeg', 'WhatsApp Image 2026-07-02 at 3.27.39 PM.jpeg', 'WhatsApp Image 2026-07-02 at 3.34.00 PM.jpeg', 'WhatsApp Image 2026-07-02 at 3.16.19 PM.jpeg', 'WhatsApp Image 2026-07-02 at 3.25.41 PM.jpeg', 'WhatsApp Image 2026-07-02 at 3.35.24 PM.jpeg', 'WhatsApp Image 2026-07-02 at 3.24.40 PM.jpeg', 'WhatsApp Image 2026-07-02 at 3.25.59 PM.jpeg', 'WhatsApp Image 2026-07-02 at 3.34.39 PM.jpeg', 'WhatsApp Image 2026-07-02 at 3.32.37 PM.jpeg']
Total: 32

In [16]:
print(os.listdir("/content/data/raw/synthetic/synthetic")[:10])
print("Total:", len(os.listdir("/content/data/raw/synthetic/synthetic")))

['3a07ff17-e297-4e55-bf13-d706d43ff6da.jpg', '27333b38-8eb5-469e-96d8-21fe2e9bb110.jpg', 'f5c9b1cf-b66e-408f-85bd-1a7093ffd9b5.jpg', '06bf5d08-9508-4cfe-9c56-77e6e0542b3b.jpg', 'd83e4fba-2dd6-4506-b7da-1db857bc4291.jpg', 'f080f490-9f0b-4dc8-aec8-117bb9523f33.jpg', '58208c93-88aa-44a8-9c26-83e8c5a5280f.jpg', '6aed97fb-773d-4820-bdc7-4f4380438fb6.jpg', '1dafb89e-a9ee-4e46-8a0b-38776f777dfb.jpg', 'c0d34bad-1740-4269-92fa-a48519f31d7e.jpg']
Total: 20

In [17]:
import csv
import os

labels = []


selected = df.head(50)

for _, row in selected.iterrows():

    filename = os.path.basename(row["file_name"])

    labels.append({
        "image": f"data/raw/dataset/{filename}",
        "text": row["text"]
    })



news_folder = "/content/data/raw/newspaper/screenshots"

for img in sorted(os.listdir(news_folder))[:30]:

    labels.append({
        "image": f"data/raw/newspaper/{img}",
        "text": "WRITE_THE_URDU_TEXT_HERE"
    })




synthetic_folder = "/content/data/raw/synthetic/synthetic"

for img in sorted(os.listdir(synthetic_folder)):

    labels.append({
        "image": f"data/raw/synthetic/{img}",
        "text": "WRITE_THE_URDU_TEXT_HERE"
    })

with open("/content/data/labels.csv","w",newline="",encoding="utf-8") as f:

    writer = csv.DictWriter(f,fieldnames=["image","text"])

    writer.writeheader()

    writer.writerows(labels)

print(len(labels))
print("labels.csv created successfully!")

100
labels.csv created successfully!

In [18]:
import pandas as pd

labels = pd.read_csv("/content/data/labels (2).csv")

labels.head(15)

,image,text
0,data/raw/dataset/0.png,پشاور،بنوں (نمائندہ جنگ،اے ایف پی) بنوں میں اق...
1,data/raw/dataset/1.png,اسکے ساتھ ملحقہ علاقے کے عوام نے بجلی و گیس \n
2,data/raw/dataset/10.png,نے بجلی وگیس کی لوڈشیڈنگ کیخلاف مظاہرہ کیا۔ مظ...
3,data/raw/dataset/100.png,نہیں آ یا۔ آخریہ کونسا مذہب ہے؟کیا اسلام کے نا...
4,data/raw/dataset/1000.png,ضرور ہے۔ انہوں نے کہا کہ میرا احمدیوں سے کوئی \n
5,data/raw/dataset/10000.png,ڈالر کی قدر میں اضافہ ہوگیا تاہم یورپین ممالک ...
6,data/raw/dataset/10001.png,اہم کرنسیوں بشمول یورو اور برطانوی پاؤنڈ کی قد...
7,data/raw/dataset/10002.png,کمی ریکارڈ کی گئی۔ منگل کو امریکی ڈالر کی قیمت \n
8,data/raw/dataset/10003.png,فروخت اور قیمت خرید میں بالترتیب 21 پیسے اور 2...
9,data/raw/dataset/10004.png,پیسے کی تیزی رہی، تاہم یورو کی قیمت فروخت میں \n
10,data/raw/dataset/10005.png,50 پیسے اور قیمت خرید میں 49 پیسے کی کمی \n
11,data/raw/dataset/10006.png,ریکارڈ کی گئی۔ اسی طرح برطانوی پاؤنڈ کی قدر می...
12,data/raw/dataset/10007.png,بھی 45 پیسے کی مندی رہی۔ نیشنل بینک آف پاکستان \n
13,data/raw/dataset/10008.png,سے جاری کردہ اعداد و شمار کے مطابق امریکی ڈالر \n
14,data/raw/dataset/10009.png,اپنی گزشتہ کاروباری روز کی قیمت فروخت 88.17 رو...

In [20]:
import pandas as pd

df_labels = pd.read_csv("/content/data/labels (2).csv")
df_labels.tail(50)

,image,text
49,data/raw/dataset/10040.png,پسند کیا جاتا ہے۔ اگرچہ ہلسا مچھلی بھارت کے با...
50,data/raw/newspaper/WhatsApp Image 2026-07-02 a...,پاکستان کرکٹ بورڈ (پی سی بی) اور سعودی عرب کرک...
51,data/raw/newspaper/WhatsApp Image 2026-07-02 a...,امریکی صدر کا کہنا ہے کہ ایران کی قیادت نے مذا...
52,data/raw/newspaper/WhatsApp Image 2026-07-02 a...,9 مئی کو ریڈیو پاکستان پر حملے میں سہیل آفریدی...
53,data/raw/newspaper/WhatsApp Image 2026-07-02 a...,معاہدے کے تحت جدید اور مربوط کرکٹ انفرا اسٹرکچ...
54,data/raw/newspaper/WhatsApp Image 2026-07-02 a...,چین، انڈیا اور عراق اربوں ڈالر کے منجمد ایرانی...
55,data/raw/newspaper/WhatsApp Image 2026-07-02 a...,سال 2025 کے بارے میں درج کرائی گئی مالیاتی رپو...
56,data/raw/newspaper/WhatsApp Image 2026-07-02 a...,927 صفحات پر مشتمل ان انکشافات میں انہوں نے ’س...
57,data/raw/newspaper/WhatsApp Image 2026-07-02 a...,ٹرمپ نے ورلڈ لبرٹی فنانشل سے 500 ملین ڈالر سے ...
58,data/raw/newspaper/WhatsApp Image 2026-07-02 a...,وائٹ ہاؤس نے اس بات کی تردید کی کہ ڈونلڈ ٹرمپ ...
59,data/raw/newspaper/WhatsApp Image 2026-07-02 a...,ٹرمپ نے بدھ کو کہا کہ سٹاک مارکیٹوں میں بہتر ہ...
60,data/raw/newspaper/WhatsApp Image 2026-07-02 a...,وائٹ ہاؤس کی نائب پریس سیکریٹری اینا کیلی نے ک...
61,data/raw/newspaper/WhatsApp Image 2026-07-02 a...,سعودی وزیر داخلہ عبدالعزیز بن سعود بن نایف کی ...
62,data/raw/newspaper/WhatsApp Image 2026-07-02 a...,شہباز شریف ایرانی سپریم لیڈر آیت اللہ خامنہ ای...
63,data/raw/newspaper/WhatsApp Image 2026-07-02 a...,پاکستان کے صوبہ خیبرپختونخوا میں حالیہ تیز بار...
64,data/raw/newspaper/WhatsApp Image 2026-07-02 a...,پاکستان کی وزارتِ خارجہ کے مطابق دوحہ میں پاکس...
65,data/raw/newspaper/WhatsApp Image 2026-07-02 a...,امریکی فوج نے اعلان کیا ہے کہ بدھ کے روز بحیرہ...
66,data/raw/newspaper/WhatsApp Image 2026-07-02 a...,امریکہ کے نائب صدر جے ڈی وینس نے کہا ہے کہ صدر...
67,data/raw/newspaper/WhatsApp Image 2026-07-02 a...,قطری وزارتِ خارجہ کے مطابق پاکستان اور قطر کے ...
68,data/raw/newspaper/WhatsApp Image 2026-07-02 a...,ایرانی پارلیمان کے سپیکر محمد باقر قالیباف نے ...
69,data/raw/newspaper/WhatsApp Image 2026-07-02 a...,سعودی عرب کے وزیر داخلہ نے پاکستانی ہم منصب مح...
70,data/raw/newspaper/WhatsApp Image 2026-07-02 a...,لاہور کے علاقے باغبانپورہ میں زیر تعمیر عمارت ...
71,data/raw/newspaper/WhatsApp Image 2026-07-02 a...,ریسکیو 1122 کے مطابق باغبانپورہ ویمن کالج روڈ ...
72,data/raw/newspaper/WhatsApp Image 2026-07-02 a...,ریسکیو 1122 کا کہنا ہے کہ پانچ افراد کو ہسپتال...
73,data/raw/newspaper/WhatsApp Image 2026-07-02 a...,ریسکیو کے مطابق تاحال بچے کی شناخت نہیں ہو سکی...
74,data/raw/newspaper/WhatsApp Image 2026-07-02 a...,جہاز رانی سے متعلق یونینوں اور کمپنیوں نے اعلا...
75,data/raw/newspaper/WhatsApp Image 2026-07-02 a...,بی بی سی فارس کے مطابق انٹرنیشنل ٹرانسپورٹ ورک...
76,data/raw/newspaper/WhatsApp Image 2026-07-02 a...,بی بی سی فارسی نے خبر رساں ادارے اے ایف پی کا ...
77,data/raw/newspaper/WhatsApp Image 2026-07-02 a...,یاد رہے کہ آبنائے ہرمز کو پہلی بار پانچ مارچ ک...
78,data/raw/newspaper/WhatsApp Image 2026-07-02 a...,یہ درجہ بندی ان بحری جہازوں پر لاگو ہوتی ہے جن...
79,data/raw/synthetic/00ae7679-3e15-4161-ad25-06d...,صبر کا پھل میٹھا ہوتا ہے
80,data/raw/synthetic/06258762-3e93-4fb5-9856-666...,تعلیم ہر انسان کا حق ہے
81,data/raw/synthetic/06bf5d08-9508-4cfe-9c56-77e...,دوستی ایک انمول رشتہ ہے
82,data/raw/synthetic/1dafb89e-a9ee-4e46-8a0b-387...,پانی زندگی کی بنیاد ہے
83,data/raw/synthetic/21ecbd37-a9bb-4e8b-8c53-247...,خوشی بانٹنے سے بڑھتی ہے
84,data/raw/synthetic/27333b38-8eb5-469e-96d8-21f...,کراچی پاکستان کا سب سے بڑا شہر ہے
85,data/raw/synthetic/3a07ff17-e297-4e55-bf13-d70...,محبت سے دل جیتے جاتے ہیں
86,data/raw/synthetic/58208c93-88aa-44a8-9c26-83e...,ورزش صحت کے لیے ضروری ہے
87,data/raw/synthetic/6aed97fb-773d-4820-bdc7-4f4...,استاد قوم کا معمار ہوتا ہے
88,data/raw/synthetic/8bdd3dc8-8776-43d6-9e17-0eb...,اردو ہماری قومی زبان ہے
89,data/raw/synthetic/9612b72d-637e-4f48-85e2-00e...,وقت کی قدر کرو
90,data/raw/synthetic/9ce4e525-86c0-4b71-8d90-574...,محنت کامیابی کی کنجی ہے
91,data/raw/synthetic/a50c5ee4-4976-4ec7-b021-3cb...,کتاب انسان کی بہترین دوست ہے
92,data/raw/synthetic/bf7b505b-471b-4799-bd65-5c3...,ایمانداری بہترین پالیسی ہے
93,data/raw/synthetic/c0d34bad-1740-4269-92fa-a48...,پاکستان زندہ باد
94,data/raw/synthetic/d20ce7c3-e893-4857-8210-c36...,آج کا موسم خوشگوار ہے
95,data/raw/synthetic/d4e83e36-8f2c-44c6-bf8f-439...,سچائی ہمیشہ فتح یاب ہوتی ہے
96,data/raw/synthetic/d83e4fba-2dd6-4506-b7da-1db...,علم انسان کو روشنی دیتا ہے
97,data/raw/synthetic/f080f490-9f0b-4dc8-aec8-117...,درخت لگانا نیکی کا کام ہے
98,data/raw/synthetic/f5c9b1cf-b66e-408f-85bd-1a7...,صحت ہی اصل دولت ہے

In [22]:
import shutil
shutil.make_archive("/content/Urdu_OCR_Project_Data","zip","/content/data")
print("Zip created successfully!")

Zip created successfully!